// Mock data for SimpleChef
import { Recipe, User, MealPlan, GroceryItem } from './types';

export const mockUser: User = {
  id: 'user-1',
  email: 'demo@simplechef.com',
  full_name: 'Alex Chef',
  bio: 'Home cook passionate about healthy meals',
  calorie_goal: 2000,
  dietary_restrictions: ['Vegetarian'],
  is_screen_always_on: true,
  profile_image_url: undefined,
};

export const mockRecipes: Recipe[] = [
  {
    id: '1',
    title: 'Classic Margherita Pizza',
    description: 'Authentic Italian pizza with fresh mozzarella, tomatoes, and basil',
    image_url: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800',
    prep_time_minutes: 20,
    cook_time_minutes: 15,
    servings: 4,
    difficulty: 'medium',
    total_calories: 800,
    protein_grams: 32,
    carbs_grams: 95,
    fat_grams: 28,
    tags: ['Italian', 'Vegetarian', 'Dinner'],
    ingredients: [
      { name: 'Pizza dough', quantity: '1', unit: 'lb', step_id: null },
      { name: 'Tomato sauce', quantity: '1', unit: 'cup', step_id: null },
      { name: 'Fresh mozzarella', quantity: '8', unit: 'oz', step_order_index: 2 },
      { name: 'Fresh basil', quantity: '1/4', unit: 'cup', step_order_index: 3 },
      { name: 'Olive oil', quantity: '2', unit: 'tbsp', step_id: null },
    ],
    steps: [
      { order_index: 1, instruction: 'Preheat oven to 475°F (245°C). Roll out pizza dough on a floured surface to desired thickness.', timer_seconds: null },
      { order_index: 2, instruction: 'Spread tomato sauce evenly over the dough, leaving a 1-inch border. Add mozzarella cheese.', timer_seconds: null },
      { order_index: 3, instruction: 'Bake in preheated oven for 12-15 minutes until crust is golden and cheese is bubbly.', timer_seconds: 900 },
      { order_index: 4, instruction: 'Remove from oven, top with fresh basil leaves and drizzle with olive oil. Let cool for 2 minutes before slicing.', timer_seconds: 120 },
    ],
    created_by_id: 'user-1',
    is_public: true,
  },
  {
    id: '2',
    title: 'Creamy Chicken Alfredo',
    description: 'Rich and creamy pasta with tender chicken breast',
    image_url: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=800',
    prep_time_minutes: 15,
    cook_time_minutes: 25,
    servings: 4,
    difficulty: 'easy',
    total_calories: 950,
    protein_grams: 45,
    carbs_grams: 85,
    fat_grams: 42,
    tags: ['Italian', 'Pasta', 'Dinner'],
    ingredients: [
      { name: 'Fettuccine pasta', quantity: '1', unit: 'lb', step_id: null },
      { name: 'Chicken breast', quantity: '1', unit: 'lb', step_order_index: 1 },
      { name: 'Heavy cream', quantity: '2', unit: 'cups', step_order_index: 3 },
      { name: 'Parmesan cheese', quantity: '1', unit: 'cup', step_order_index: 3 },
      { name: 'Garlic', quantity: '3', unit: 'cloves', step_order_index: 2 },
      { name: 'Butter', quantity: '4', unit: 'tbsp', step_order_index: 2 },
    ],
    steps: [
      { order_index: 1, instruction: 'Season chicken with salt and pepper. Cook in a skillet over medium-high heat until golden and cooked through, about 6-8 minutes per side.', timer_seconds: 480 },
      { order_index: 2, instruction: 'Remove chicken and set aside. In the same skillet, melt butter and sauté minced garlic until fragrant, about 1 minute.', timer_seconds: 60 },
      { order_index: 3, instruction: 'Add heavy cream and bring to a simmer. Stir in Parmesan cheese until melted and sauce thickens, about 5 minutes.', timer_seconds: 300 },
      { order_index: 4, instruction: 'Meanwhile, cook fettuccine according to package directions. Drain and toss with sauce. Slice chicken and serve on top.', timer_seconds: null },
    ],
    created_by_id: 'user-1',
    is_public: true,
  },
  {
    id: '3',
    title: 'Avocado Toast Supreme',
    description: 'Elevated avocado toast with poached egg and cherry tomatoes',
    image_url: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800',
    prep_time_minutes: 10,
    cook_time_minutes: 5,
    servings: 2,
    difficulty: 'easy',
    total_calories: 350,
    protein_grams: 18,
    carbs_grams: 35,
    fat_grams: 16,
    tags: ['Breakfast', 'Vegetarian', 'Quick'],
    ingredients: [
      { name: 'Sourdough bread', quantity: '4', unit: 'slices', step_id: null },
      { name: 'Ripe avocados', quantity: '2', unit: 'whole', step_order_index: 1 },
      { name: 'Eggs', quantity: '4', unit: 'whole', step_order_index: 2 },
      { name: 'Cherry tomatoes', quantity: '1', unit: 'cup', step_order_index: 1 },
      { name: 'Lemon juice', quantity: '1', unit: 'tbsp', step_order_index: 1 },
      { name: 'Red pepper flakes', quantity: '1/4', unit: 'tsp', step_order_index: 3 },
    ],
    steps: [
      { order_index: 1, instruction: 'Toast bread slices until golden. Mash avocados with lemon juice, salt, and pepper. Halve cherry tomatoes.', timer_seconds: null },
      { order_index: 2, instruction: 'Bring a pot of water to a gentle simmer. Crack eggs into water and poach for 3-4 minutes until whites are set.', timer_seconds: 240 },
      { order_index: 3, instruction: 'Spread mashed avocado on toast. Top with poached eggs, cherry tomatoes, and sprinkle with red pepper flakes.', timer_seconds: null },
    ],
    created_by_id: 'user-1',
    is_public: true,
  },
  {
    id: '4',
    title: 'Thai Green Curry',
    description: 'Aromatic coconut curry with vegetables and tofu',
    image_url: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800',
    prep_time_minutes: 20,
    cook_time_minutes: 30,
    servings: 4,
    difficulty: 'medium',
    total_calories: 520,
    tags: ['Thai', 'Vegetarian', 'Dinner', 'Spicy'],
    ingredients: [
      { name: 'Green curry paste', quantity: '3', unit: 'tbsp', step_order_index: 2 },
      { name: 'Coconut milk', quantity: '2', unit: 'cans', step_order_index: 2 },
      { name: 'Firm tofu', quantity: '14', unit: 'oz', step_order_index: 1 },
      { name: 'Bell peppers', quantity: '2', unit: 'whole', step_order_index: 3 },
      { name: 'Bamboo shoots', quantity: '1', unit: 'cup', step_order_index: 3 },
      { name: 'Thai basil', quantity: '1/2', unit: 'cup', step_order_index: 4 },
      { name: 'Jasmine rice', quantity: '2', unit: 'cups', step_id: null },
    ],
    steps: [
      { order_index: 1, instruction: 'Press and cube tofu. Cook rice according to package directions.', timer_seconds: null },
      { order_index: 2, instruction: 'In a large pan, heat curry paste for 1 minute. Add coconut milk and bring to a simmer.', timer_seconds: 60 },
      { order_index: 3, instruction: 'Add tofu, sliced bell peppers, and bamboo shoots. Simmer for 15 minutes until vegetables are tender.', timer_seconds: 900 },
      { order_index: 4, instruction: 'Stir in Thai basil leaves. Serve hot over jasmine rice.', timer_seconds: null },
    ],
    created_by_id: 'user-1',
    is_public: true,
  },
  {
    id: '5',
    title: 'Mediterranean Quinoa Bowl',
    description: 'Healthy bowl with quinoa, falafel, and fresh vegetables',
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
    prep_time_minutes: 15,
    cook_time_minutes: 20,
    servings: 2,
    difficulty: 'easy',
    total_calories: 480,
    tags: ['Healthy', 'Vegetarian', 'Lunch', 'Mediterranean'],
    ingredients: [
      { name: 'Quinoa', quantity: '1', unit: 'cup', step_id: null },
      { name: 'Falafel', quantity: '6', unit: 'pieces', step_order_index: 1 },
      { name: 'Cherry tomatoes', quantity: '1', unit: 'cup', step_order_index: 2 },
      { name: 'Cucumber', quantity: '1', unit: 'whole', step_order_index: 2 },
      { name: 'Hummus', quantity: '1/2', unit: 'cup', step_order_index: 3 },
      { name: 'Tahini sauce', quantity: '1/4', unit: 'cup', step_order_index: 3 },
    ],
    steps: [
      { order_index: 1, instruction: 'Cook quinoa according to package directions. Prepare falafel per package instructions (bake or fry).', timer_seconds: null },
      { order_index: 2, instruction: 'While quinoa cooks, chop cucumber and halve cherry tomatoes.', timer_seconds: null },
      { order_index: 3, instruction: 'Divide quinoa into bowls. Top with falafel, vegetables, hummus, and drizzle with tahini sauce.', timer_seconds: null },
    ],
    created_by_id: 'user-1',
    is_public: true,
  },
  {
    id: '6',
    title: 'Blueberry Pancakes',
    description: 'Fluffy pancakes loaded with fresh blueberries',
    image_url: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=800',
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    difficulty: 'easy',
    total_calories: 420,
    tags: ['Breakfast', 'Vegetarian', 'Quick'],
    ingredients: [
      { name: 'All-purpose flour', quantity: '2', unit: 'cups', step_id: null },
      { name: 'Milk', quantity: '1.5', unit: 'cups', step_order_index: 1 },
      { name: 'Eggs', quantity: '2', unit: 'whole', step_order_index: 1 },
      { name: 'Fresh blueberries', quantity: '1', unit: 'cup', step_order_index: 2 },
      { name: 'Butter', quantity: '4', unit: 'tbsp', step_order_index: 1 },
      { name: 'Maple syrup', quantity: 'to taste', unit: '', step_order_index: 3 },
    ],
    steps: [
      { order_index: 1, instruction: 'In a bowl, whisk together flour, milk, eggs, melted butter, sugar, baking powder, and salt until smooth.', timer_seconds: null },
      { order_index: 2, instruction: 'Heat a griddle over medium heat. Pour 1/4 cup batter per pancake. Add blueberries to each. Cook until bubbles form, about 2-3 minutes, then flip.', timer_seconds: 180 },
      { order_index: 3, instruction: 'Cook another 2 minutes until golden. Serve warm with maple syrup and extra blueberries.', timer_seconds: 120 },
    ],
    created_by_id: 'user-1',
    is_public: true,
  },
];

export const mockMealPlans: MealPlan[] = [
  {
    id: 'mp-1',
    date: '2026-04-20',
    meal_type: 'breakfast',
    recipe_id: '3',
    recipe_title: 'Avocado Toast Supreme',
    calories: 350,
    protein_grams: 18,
    carbs_grams: 35,
    fat_grams: 16,
    user_id: 'user-1',
  },
  {
    id: 'mp-2',
    date: '2026-04-20',
    meal_type: 'lunch',
    recipe_id: '5',
    recipe_title: 'Mediterranean Quinoa Bowl',
    calories: 480,
    protein_grams: 15,
    carbs_grams: 62,
    fat_grams: 18,
    user_id: 'user-1',
  },
  {
    id: 'mp-3',
    date: '2026-04-20',
    meal_type: 'dinner',
    recipe_id: '1',
    recipe_title: 'Classic Margherita Pizza',
    calories: 800,
    protein_grams: 32,
    carbs_grams: 95,
    fat_grams: 28,
    user_id: 'user-1',
  },
  {
    id: 'mp-4',
    date: '2026-04-21',
    meal_type: 'breakfast',
    recipe_id: '6',
    recipe_title: 'Blueberry Pancakes',
    calories: 420,
    protein_grams: 12,
    carbs_grams: 65,
    fat_grams: 14,
    user_id: 'user-1',
  },
  {
    id: 'mp-5',
    date: '2026-04-21',
    meal_type: 'lunch',
    custom_food_name: 'Caesar Salad',
    calories: 350,
    protein_grams: 25,
    carbs_grams: 12,
    fat_grams: 22,
    user_id: 'user-1',
  },
  {
    id: 'mp-6',
    date: '2026-04-22',
    meal_type: 'dinner',
    recipe_id: '4',
    recipe_title: 'Thai Green Curry',
    calories: 520,
    protein_grams: 28,
    carbs_grams: 48,
    fat_grams: 24,
    user_id: 'user-1',
  },
];

export const mockGroceryItems: GroceryItem[] = [
  { id: 'g-1', name: 'Fresh mozzarella', quantity: '8', unit: 'oz', category: 'Dairy', is_checked: false, user_id: 'user-1' },
  { id: 'g-2', name: 'Fresh basil', quantity: '1', unit: 'bunch', category: 'Produce', is_checked: false, user_id: 'user-1' },
  { id: 'g-3', name: 'Tomato sauce', quantity: '1', unit: 'jar', category: 'Canned Goods', is_checked: true, user_id: 'user-1' },
  { id: 'g-4', name: 'Ripe avocados', quantity: '4', unit: 'whole', category: 'Produce', is_checked: false, user_id: 'user-1' },
  { id: 'g-5', name: 'Eggs', quantity: '1', unit: 'dozen', category: 'Dairy', is_checked: false, user_id: 'user-1' },
  { id: 'g-6', name: 'Sourdough bread', quantity: '1', unit: 'loaf', category: 'Bakery', is_checked: true, user_id: 'user-1' },
  { id: 'g-7', name: 'Cherry tomatoes', quantity: '2', unit: 'cups', category: 'Produce', is_checked: false, user_id: 'user-1' },
  { id: 'g-8', name: 'Olive oil', quantity: '1', unit: 'bottle', category: 'Pantry', is_checked: true, user_id: 'user-1' },
];
